# Generated by Django 4.0 on 2022-05-28 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField(verbose_name='Date Of Birth')),
                ('email', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField(verbose_name='Contact No')),
                ('state', models.SmallIntegerField(choices=[(1, 'customer'), (2, 'localseller'), (3, 'admin')], default=1, verbose_name='User State')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Registered')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Last Login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=10, verbose_name='Package Name')),
                ('package_price', models.IntegerField(verbose_name='Package Price')),
                ('package_duration', models.CharField(max_length=25, verbose_name='Package Duration')),
                ('package_description', models.CharField(max_length=1000, verbose_name='Package Description')),
                ('package_keywords', models.IntegerField(default=0, verbose_name='Package Keywords')),
                ('package_price_id', models.CharField(default='', max_length=150, verbose_name='Package Price ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('product_description', models.CharField(max_length=1000, verbose_name='Product Description')),
                ('product_image', models.CharField(max_length=1500, verbose_name='Product Image')),
                ('min_price', models.IntegerField(default=0, verbose_name='Minimum Price')),
                ('max_price', models.IntegerField(default=0, verbose_name='Maximum Price')),
                ('offered_by', models.IntegerField(default=0, verbose_name='Offered By')),
                ('category_name', models.CharField(default='', max_length=200, verbose_name='Category Name')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100, verbose_name='SubCategory Name')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviewStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.IntegerField(verbose_name='Positive Reviews Count')),
                ('neutral', models.IntegerField(verbose_name='Neutral Reviews Count')),
                ('negative', models.IntegerField(verbose_name='Negative Reviews Count')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_reviews', models.CharField(max_length=1000, verbose_name='Product Reviews')),
                ('review_type', models.SmallIntegerField(choices=[(1, 'positive'), (2, 'neutral'), (3, 'negative')], default=1, verbose_name='Review Type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.subcategory', verbose_name='Sub Category'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_site', models.CharField(max_length=1000, verbose_name='Reference Site')),
                ('product_price', models.CharField(max_length=6, verbose_name='Product Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='PackageConsumedDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keywords_count', models.IntegerField(default=0, verbose_name='Keywords Count')),
                ('state', models.BooleanField(default=True, verbose_name='state')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.package')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='LocalSellerUploadedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_state', models.SmallIntegerField(choices=[(1, 'Not Done'), (2, 'In Process'), (3, 'Done')], default=1, verbose_name='File State')),
                ('ls_product_file', models.FileField(default=False, upload_to='media/LocalSellerData/', verbose_name='Upload CSV File')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='LocalSellerDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100, verbose_name='Shop Name')),
                ('shop_address', models.CharField(max_length=1000, verbose_name='Shop Address')),
                ('local_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
