# Generated by Django 4.0 on 2022-01-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=50)),
                ('CPassword', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField()),
                ('Email', models.CharField(max_length=50)),
                ('ContactNo', models.IntegerField()),
            ],
        ),
    ]
