# Generated by Django 4.0 on 2022-02-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('product_description', models.CharField(max_length=1000, verbose_name='Product Description')),
                ('product_image', models.CharField(max_length=1500, verbose_name='Product Image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_reviews', models.CharField(max_length=1000, verbose_name='Product Reviews')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_site', models.CharField(max_length=1000, verbose_name='Reference Site')),
                ('product_price', models.IntegerField(verbose_name='Product Price')),
                ('min_price', models.IntegerField(verbose_name='Minimum Price')),
                ('max_price', models.IntegerField(verbose_name='Maximum Price')),
                ('offered_by', models.IntegerField(default=False, verbose_name='Offered By')),
                ('product_file', models.FileField(default=False, upload_to='LocalSellerData/', verbose_name='Upload CSV File')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
