# Generated by Django 4.0 on 2022-05-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='walmart_id',
            field=models.CharField(default='', max_length=200, verbose_name='Walmart Id'),
        ),
    ]
