# Generated by Django 4.0 on 2022-05-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_walmart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraningData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=1000, verbose_name='Review Text')),
                ('review_type', models.SmallIntegerField(choices=[(1, 'positive'), (2, 'neutral'), (3, 'negative')], default=1, verbose_name='Review Type')),
            ],
        ),
    ]
