# Generated by Django 4.0 on 2022-05-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_traningdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviewstats',
            name='negative',
            field=models.IntegerField(default=0, verbose_name='Negative Reviews Count'),
        ),
        migrations.AlterField(
            model_name='productreviewstats',
            name='neutral',
            field=models.IntegerField(default=0, verbose_name='Neutral Reviews Count'),
        ),
        migrations.AlterField(
            model_name='productreviewstats',
            name='positive',
            field=models.IntegerField(default=0, verbose_name='Positive Reviews Count'),
        ),
    ]
